### ISSUE TITLE
Button for database and link under tools not displaying phpMyAdmin

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/ds-phpmyadmin#2]
OS Windows 10
DS 5.0
phpMyAdmin Plugin 5.1.1

When activating no display of [ Database ] button on localhost page or a link to the phpMyAdmin under tools

**Comment by Steveorevo** [comment]
This issue is related to missing version number in the release; it should be resolved in latest release:
https://github.com/ServerPress/ds-phpmyadmin/commit/b9bccac82e914e9003abcc5945ed768bba4747fe

**Comment by GreggFranklin** [comment]
Issue resolved with Release of version 1.0
